declare function ChatAdminLoad(): void;
declare function ChatAdminRun(): void;
declare function ChatAdminClick(): void;
declare function ChatAdminExit(): void;
declare function ChatAdminResponse(data: any): void;
declare function ChatAdminUpdateRoom(): void;
declare var ChatAdminBackground: string;
declare var ChatAdminMessage: string;
declare var ChatAdminPrivate: boolean;
declare var ChatAdminBackgroundIndex: number;
declare var ChatAdminBackgroundSelect: string;
declare var ChatAdminLocked: boolean;
declare var ChatAdminBackgroundSelected: any;
