declare function TherapyLoad(): void;
declare function TherapyRun(): void;
declare function TherapyVerifyEnd(): void;
declare function TherapyDoMove(MoveType: any): void;
declare function TherapyClick(): void;
declare var TherapyBackground: string;
declare var TherapyCharacterLeft: any;
declare var TherapyCharacterRight: any;
declare var TherapyMoves: number[];
declare var TherapyGenerateMoveTimer: number;
declare var TherapyStress: number;
