declare function ActivityAllowed(): boolean;
declare function ActivityDictionaryLoad(): void;
declare function ActivityDictionaryText(KeyWord: any): any;
declare function ActivityDialogBuild(C: any): void;
declare function ActivityEffect(S: any, C: any, A: any, Z: any): void;
declare function ActivityChatRoomArousalSync(C: any): void;
declare function ActivitySetArousal(C: any, Progress: any): void;
declare function ActivitySetArousalTimer(C: any, Activity: any, Zone: any, Progress: any): void;
declare function ActivityOrgasmProgressBar(X: any, Y: any): void;
declare function ActivityOrgasmWillpowerProgress(C: any): void;
declare function ActivityOrgasmStart(C: any): void;
declare function ActivityOrgasmStop(C: any, Progress: any): void;
declare function ActivityOrgasmGameGenerate(Progress: any): void;
declare function ActivityOrgasmPrepare(C: any): void;
declare function ActivityExpression(C: any, Progress: any): void;
declare function ActivityTimerProgress(C: any, Progress: any): void;
declare function ActivityRunSelf(Source: any, Target: any, Activity: any): void;
declare function ActivityRun(C: any, Activity: any): void;
declare function ActivityArousalItem(Source: any, Target: any, Asset: any): void;
declare var ActivityDictionary: any;
declare var ActivityOrgasmGameButtonX: number;
declare var ActivityOrgasmGameButtonY: number;
declare var ActivityOrgasmGameProgress: number;
declare var ActivityOrgasmGameDifficulty: number;
declare var ActivityOrgasmGameResistCount: number;
declare var ActivityOrgasmGameTimer: number;
declare var ActivityOrgasmResistLabel: string;
