declare function AfkTimerReset(): void;
declare function AfkTimerIncrement(): void;
declare function AfkTimerStart(): void;
declare function AfkTimerStop(): void;
declare function AfkTimerSetEnabled(Enabled: any): void;
declare function AfkTimerSetIsAfk(): void;
declare var AfkTimerIncrementMs: number;
declare var AfkTimerTimout: number;
declare var AfkTimerIdle: number;
declare var AfkTimerIsSet: boolean;
declare var AfkTimerIsEnabled: any;
declare var AfkTimerEventsList: string[];
declare var AfkTimerID: any;
