declare function CharacterReset(CharacterID: any, CharacterAssetFamily: any): void;
declare function CharacterRandomName(C: any): void;
declare function CharacterBuildDialog(C: any, CSV: any): void;
declare function CharacterLoadCSVDialog(C: any, Override: any): void;
declare function CharacterArchetypeClothes(C: any, Archetype: any, ForceColor: any): void;
declare function CharacterLoadNPC(NPCType: any): any;
declare function CharacterOnlineRefresh(Char: any, data: any, SourceMemberNumber: any): void;
declare function CharacterLoadOnline(data: any, SourceMemberNumber: any): any;
declare function CharacterDelete(NPCType: any): void;
declare function CharacterAddPose(C: any, NewPose: any): void;
declare function CharacterLoadPose(C: any): void;
declare function CharacterAddEffect(C: any, NewEffect: any): void;
declare function CharacterLoadEffect(C: any): void;
declare function CharacterLoadCanvas(C: any): void;
declare function CharacterLoadCanvasAll(): void;
declare function CharacterSetCurrent(C: any): void;
declare function CharacterChangeMoney(C: any, Value: any): void;
declare function CharacterRefresh(C: any, Push: any): void;
declare function CharacterHasNoItem(C: any): boolean;
declare function CharacterIsNaked(C: any): boolean;
declare function CharacterIsInUnderwear(C: any): boolean;
declare function CharacterNaked(C: any): void;
declare function CharacterRandomUnderwear(C: any): void;
declare function CharacterUnderwear(C: any, Appearance: any): void;
declare function CharacterDress(C: any, Appearance: any): void;
declare function CharacterRelease(C: any): void;
declare function CharacterReleaseFromLock(C: any, LockName: any): void;
declare function CharacterReleaseNoLock(C: any): void;
declare function CharacterGetBonus(C: any, BonusType: any): number;
declare function CharacterFullRandomRestrain(C: any, Ratio: any): void;
declare function CharacterSetActivePose(C: any, NewPose: any): void;
declare function CharacterSetFacialExpression(C: any, AssetGroup: any, Expression: any, Timer: any): void;
declare function CharacterResetFacialExpression(C: any): void;
declare function CharacterGetCurrent(): any;
declare function CharacterCompressWardrobe(Wardrobe: any): any;
declare function CharacterDecompressWardrobe(Wardrobe: any): any;
declare var Character: any[];
