declare function DrawHexToRGB(color: any): {
    r: number;
    g: number;
    b: number;
};
declare function DrawRGBToHex(rgb: any): string;
declare function DrawLoad(): void;
declare function DrawGetImage(Source: any): any;
declare function DrawGetImageOnLoad(Img: any): void;
declare function DrawGetImageOnError(Img: any, IsAsset: any): void;
declare function DrawArousalThermometer(X: any, Y: any, Zoom: any, Progress: any, Automatic: any, Orgasm: any): void;
declare function DrawArousalMeter(C: any, X: any, Y: any, Zoom: any): void;
declare function DrawCharacter(C: any, X: any, Y: any, Zoom: any, IsHeightResizeAllowed: any): void;
declare function DrawAssetGroupZone(C: any, Zone: any, HeightRatio: any, X: any, Y: any, Color: any, Thickness?: number): void;
declare function DrawAssetGroupZoneBackground(C: any, Zone: any, HeightRatio: any, X: any, Y: any, Color: any): void;
declare function DrawImageZoomCanvas(Source: any, Canvas: any, SX: any, SY: any, SWidth: any, SHeight: any, X: any, Y: any, Width: any, Height: any): boolean;
declare function DrawImageResize(Source: any, X: any, Y: any, Width: any, Height: any): boolean;
declare function DrawImageCanvas(Source: any, Canvas: any, X: any, Y: any): boolean;
declare function DrawCanvas(Canvas: any, X: any, Y: any): void;
declare function DrawCanvasZoom(Canvas: any, X: any, Y: any, Zoom: any): void;
declare function DrawImageZoomMirror(Source: any, SX: any, SY: any, SWidth: any, SHeight: any, X: any, Y: any, Width: any, Height: any): boolean;
declare function DrawImage(Source: any, X: any, Y: any): boolean;
declare function DrawImageCanvasColorize(Source: any, Canvas: any, X: any, Y: any, Zoom: any, HexColor: any, FullAlpha: any): boolean;
declare function DrawImageMirror(Source: any, X: any, Y: any): boolean;
declare function GetWrapTextSize(Text: any, Width: any, MaxLine: any): any;
declare function DrawTextWrap(Text: any, X: any, Y: any, Width: any, Height: any, ForeColor: any, BackColor: any, MaxLine: any): void;
declare function DrawTextFit(Text: any, X: any, Y: any, Width: any, Color: any): void;
declare function DrawText(Text: any, X: any, Y: any, Color: any, BackColor: any): void;
declare function DrawButton(Left: any, Top: any, Width: any, Height: any, Label: any, Color: any, Image: any, HoveringText: any): void;
declare function DrawCheckbox(Left: any, Top: any, Width: any, Height: any, Text: any, IsChecked: any): void;
declare function DrawBackNextButton(Left: any, Top: any, Width: any, Height: any, Label: any, Color: any, Image: any, BackText: any, NextText: any): void;
declare function DrawButtonHover(Left: any, Top: any, Width: any, Height: any, HoveringText: any): void;
declare function DrawEmptyRect(Left: any, Top: any, Width: any, Height: any, Color: any, Thickness?: number): void;
declare function DrawRect(Left: any, Top: any, Width: any, Height: any, Color: any): void;
declare function DrawCircle(CenterX: any, CenterY: any, Radius: any, LineWidth: any, LineColor: any): void;
declare function DrawProgressBar(X: any, Y: any, W: any, H: any, Progress: any): void;
declare function DrawProcess(): void;
declare function DrawItemPreview(X: any, Y: any, Item: any): void;
declare var MainCanvas: any;
declare var ColorCanvas: any;
declare var DrawCacheImage: {};
declare var DrawCacheLoadedImages: number;
declare var DrawCacheTotalImages: number;
declare var DrawScreenWidth: number;
declare var DrawScreenHeight: number;
