export declare function compressToBase64(input: any): string;
export declare function decompressFromBase64(input: any): string;
export declare function compressToUTF16(input: any): string;
export declare function decompressFromUTF16(compressed: any): string;
export declare function compressToUint8Array(uncompressed: any): Uint8Array;
export declare function decompressFromUint8Array(compressed: any): string;
export declare function compressToEncodedURIComponent(input: any): string;
export declare function decompressFromEncodedURIComponent(input: any): string;
export declare function compress(uncompressed: any): string;
export declare function _compress(uncompressed: any, bitsPerChar: any, getCharFromInt: any): string;
export declare function decompress(compressed: any): string;
export declare function _decompress(length: any, resetValue: any, getNextValue: any): string;
