declare function MiniGameStart(GameType: any, Difficulty: any, ReturnFunction: any): void;
declare var MiniGameType: string;
declare var MiniGameVictory: boolean;
declare var MiniGamePerfect: boolean;
declare var MiniGameDifficulty: string;
declare var MiniGameDifficultyRatio: number;
declare var MiniGameAdvancedPayment: number;
declare var MiniGameReturnFunction: string;
declare var MiniGameProgress: number;
declare var MiniGameTimer: number;
declare var MiniGameEnded: boolean;
