declare function ServerInit(): void;
declare function ServerInfo(data: any): void;
declare function ServerDisconnect(data: any): void;
declare function ServerSend(Message: any, Data: any): void;
declare function ServerPlayerSync(): void;
declare function ServerPlayerInventorySync(): void;
declare function ServerPlayerLogSync(): void;
declare function ServerPlayerReputationSync(): void;
declare function ServerPlayerSkillSync(): void;
declare function ServerAppearanceBundle(Appearance: any): {
    Group: any;
    Name: any;
    Color: any;
    Difficulty: any;
    Property: any;
}[];
declare function ServerValidateProperties(C: any, Item: any): void;
declare function ServerAppearanceLoadFromBundle(C: any, AssetFamily: any, Bundle: any, SourceMemberNumber: any): any[];
declare function ServerPlayerAppearanceSync(): void;
declare function ServerPrivateCharacterSync(): void;
declare function ServerAccountQueryResult(data: any): void;
declare function ServerAccountBeep(data: any): void;
declare function ServerDrawBeep(): void;
declare function ServerAccountOwnership(data: any): void;
declare function ServerAccountLovership(data: any): void;
declare var ServerSocket: any;
declare var ServerURL: string;
declare var ServerRelog: any;
declare var ServerBeep: {};
declare var ServerBeepAudio: HTMLAudioElement;
