declare function CharacterAppearanceBuildAssets(C: any): void;
declare function CharacterAppearanceValidate(C: any): void;
declare function CharacterAppearanceSetDefault(C: any): void;
declare function CharacterAppearanceRequired(C: any, GroupName: any): boolean;
declare function CharacterAppearanceMustHide(C: any, GroupName: any): boolean;
declare function CharacterAppearanceFullRandom(C: any, ClothOnly: any): void;
declare function CharacterAppearanceNaked(C: any): void;
declare function CharacterAppearanceStripLayer(C: any): void;
declare function CharacterAppearanceSort(AP: any): any;
declare function CharacterAppearanceVisible(C: any, AssetName: any, GroupName: any): boolean;
declare function CharacterApperanceSetHeightModifier(C: any): void;
declare function CharacterAppearanceBuildCanvas(C: any): void;
declare function CharacterAppearanceGetCurrentValue(C: any, Group: any, Type: any): any;
declare function AppearanceLoad(): void;
declare function AppearanceRun(): void;
declare function CharacterAppearanceSetItem(C: any, Group: any, ItemAsset: any, NewColor: any, DifficultyFactor: any, Refresh: any): void;
declare function CharacterAppearanceNextItem(C: any, Group: any, Forward: any, Description: any): any;
declare function CharacterAppearanceNextColor(C: any, Group: any): void;
declare function CharacterAppearanceMoveOffset(Move: any): void;
declare function CharacterAppearanceSetColorForGroup(C: any, Color: any, Group: any): void;
declare function AppearanceClick(): void;
declare function AppearanceExit(): void;
declare function CharacterAppearanceExit(C: any): void;
declare function CharacterAppearanceReady(C: any): void;
declare function CharacterAppearanceCopy(FromC: any, ToC: any): void;
declare function CharacterAppearanceLoadCharacter(C: any): void;
declare function CharacterAppearanceWardrobeLoad(C: any): void;
declare var AppearanceBackground: string;
declare var CharacterAppearanceOffset: number;
declare var CharacterAppearanceNumPerPage: number;
declare var CharacterAppearanceHeaderText: string;
declare var CharacterAppearanceBackup: any;
declare var CharacterAppearanceAssets: any[];
declare var CharacterAppearanceColorPicker: string;
declare var CharacterAppearanceColorPickerBackup: string;
declare var CharacterAppearanceColorPickerRefreshTimer: any;
declare var CharacterAppearanceSelection: any;
declare var CharacterAppearanceReturnRoom: string;
declare var CharacterAppearanceReturnModule: string;
declare var CharacterAppearanceWardrobeOffset: number;
declare var CharacterAppearanceWardrobeMode: boolean;
declare var CharacterAppearanceWardrobeText: string;
declare var CharacterAppearanceForceUpCharacter: number;
