declare function NurseryPlayerIsPacified(): boolean;
declare function NurseryPlayerIsHarnessPacified(): boolean;
declare function NurseryPlayerLostBinky(): boolean;
declare function NurseryPlayerLostBinkyAgain(): any;
declare function NurseryPlayerWearingBabyDress(): boolean;
declare function NurseryPlayerReadyToAppologise(): boolean;
declare function NurseryPlayerDiapered(): boolean;
declare function NurseryPlayerReadyDiapered(): boolean;
declare function NurseryLoad(): void;
declare function NurseryRun(): void;
declare function NurseryClick(): void;
declare function NurseryDrawText(): void;
declare function NurseryLoadNurse(): void;
declare function NurseryClothCheck(): void;
declare function NurseryNurseOutfitForNPC(CurrentNPC: any): void;
declare function NurseryABDLOutfitForNPC(CurrentNPC: any): void;
declare function NurseryNPCResrained(CurrentNPC: any, RestraintSet: any): void;
declare function NurseryRandomDressSelection(): void;
declare function NurseryRandomColorSelection(): void;
declare function NurseryDeleteItem(): void;
declare function NurseryPlayerUndress(Cost: any): void;
declare function NurseryPlayerGetsDiapered(DomChange: any): void;
declare function NurseryPlayerAdmitted(): void;
declare function NurseryPlayerWearBabyDress(): void;
declare function NurseryPlayerRestrained(RestraintSet: any): void;
declare function NurseryAddLock(C: any, LockItem: any): void;
declare function NurseryPlayerRePacified(): void;
declare function NurseryPlayerDePacified(): void;
declare function NurseryPlayerRedressed(): void;
declare function NurseryBadBabies(): void;
declare function NurseryPlayerSkillsAmnesia(): void;
declare function NurseryReplaceSkill(): void;
declare function NurseryPlayerChangeDress(): void;
declare function NurseryPlayerChangeDressColor(): void;
declare function NurseryPlayerRemoveDress(): void;
declare function NurseryPlayerCuteRelpy(): void;
declare function NurseryEscapeGate(): void;
declare function NurseryPlayerForgiven(): void;
declare function NurseryPlayerReadmitted(): void;
declare function NurseryPlayerRemoveCloth(): void;
declare function NurseryPlayerNeedsPunishing(Severity: any): void;
declare function NurseryPlayerPunished(Severity: any): void;
declare function NurseryGoodBehaviour(): void;
declare var NurseryBackground: string;
declare var NurserySituation: any;
declare var NurseryJustClicked: any;
declare var NurseryNurse: any;
declare var NurseryABDL1: any;
declare var NurseryABDL2: any;
declare var NurseryPlayerBadBabyStatus: number;
declare var NurseryPlayerInappropriateCloth: any;
declare var NurseryCoolDownTime: number;
declare var NurseryPlayerAppearance: any;
declare var RandomNumber: number;
declare var RandomResult: any;
declare var RandomResultB: any;
declare var PreviousDress: string;
declare var PreviousDressColor: string;
declare var NurseryPlayerKeepsLoosingBinky: any;
declare var NurseryGateMsg: any;
declare var NurseryLeaveMsg: any;
declare var NurseryEscapeAttempts: any;
declare var NursuryEscapeFailMsg: any;
declare var NurseryRepeatOffender: any;
declare var NurseryRegressedTalk: any;
