declare function SarahStatusIs(QueryStatus: any): boolean;
declare function SarahAmandaStatusIs(QueryStatus: any): boolean;
declare function SarahCanKissLover(): boolean;
declare function SarahCanKissNotLover(): boolean;
declare function SarahCanSpankOwner(): boolean;
declare function SarahCanSpankNotOwner(): boolean;
declare function SarahCanReleaseToClub(): boolean;
declare function SarahCanInviteToRoomFriend(): boolean;
declare function SarahCanInviteToRoomSlave(): boolean;
declare function SarahCanInviteAmandaToRoom(): boolean;
declare function SarahCanInviteAmandaToRoomRefuse(): boolean;
declare function SarahCanInviteSophieToRoom(): boolean;
declare function SarahCanInviteSophieToRoomAccept(): boolean;
declare function SarahCanInviteSophieToRoomRefuse(): boolean;
declare function SarahCanKickAmandaOut(): boolean;
declare function SarahCanKickAmandaOutRefuse(): boolean;
declare function SarahShackled(): boolean;
declare function SarahAmandaHasStrapon(): boolean;
declare function SarahAmandaHasNoStrapon(): boolean;
declare function SarahKnowAmandaInRoom(): any;
declare function SarahAmandaCanKiss(): boolean;
declare function SarahIsClubSlave(): boolean;
declare function SarahCanKissSophie(): any;
declare function SarahCanFightSophie(): any;
declare function SarahSophiePunishmentStageIs(Stage: any): boolean;
declare function SarahSophieLikesPlayer(): boolean;
declare function SarahCanStrip(): boolean;
declare function SarahIsInside(): boolean;
declare function SarahAmandaIsInside(): boolean;
declare function SarahAndAmandaAreInside(): boolean;
declare function SarahOrAmandaAreInside(): boolean;
declare function SarahIsPlayerSlave(): boolean;
declare function SarahAmandaIsPlayerSlave(): boolean;
declare function SarahAmandaAndSarahArePlayerSlave(): boolean;
declare function SarahRoomLabel(): "ExploreClub" | "SearchSarah" | "SarahBedroom";
declare function SarahSetStatus(): void;
declare function SarahLoad(): void;
declare function AmandaLoad(): void;
declare function SophieLoad(): void;
declare function SarahLoadNewCharacter(): void;
declare function SarahLoadBackground(): void;
declare function SarahRun(): void;
declare function SarahClick(): void;
declare function SarahActivityRun(): void;
declare function SarahCheckShackles(): void;
declare function SarahStartUnlockQuest(): void;
declare function SarahUnlock(): void;
declare function SarahEvasion(): void;
declare function SarahLeaveRoom(): void;
declare function SarahTransferToRoom(): void;
declare function SarahAmandaLeaveRoom(): void;
declare function SarahSophieLeaveRoom(): void;
declare function SarahTransferAmandaToRoom(): void;
declare function SarahUpsetSophie(Offset: any): void;
declare function SarahRestrainedBySophie(Phase: any, DomRep: any): void;
declare function SarahFightSophie(): void;
declare function SarahFightSophieEnd(): void;
declare function SarahSophiePunishGirls(): void;
declare function SarahSophieFreeSarahAndLeave(): void;
declare function SarahSophieFreePlayerAndAmandaTheyLeave(): void;
declare function SarahKickPlayerOut(): void;
declare function SarahTransferSophieToRoom(Love: any): void;
declare function SarahSophieSetPunishmentIntro(DomRep: any): void;
declare function SarahSophiePreparePunishCharacter(C: any): void;
declare function SarahSophieStartBuzz(C: any, Intensity: any): void;
declare function SarahSophiePunishEvent(EventType: any, DomRep: any): void;
declare function SarahSophieOrgasmGame(Factor: any): void;
declare function SarahSophieReleaseEveryoneButSarah(): void;
declare function SarahPlayerPunishGirls(): void;
declare function SarahSlaveNakedWithoutRestrains(C: any): any;
declare function SarahSlaveWithClampEggPlug(C: any): any;
declare function SarahSlaveChaste(C: any): any;
declare function SarahSlaveLockedCuffs(C: any): any;
declare function SarahSlaveOrgasm(C: any): any;
declare function SarahGiveFirstSlaveItem(C: any): void;
declare function SarahGiveSecondSlaveItem(C: any): void;
declare function SarahGiveThirdSlaveItem(C: any): void;
declare function SarahGiveFourthSlaveItem(C: any): void;
declare function SarahSlaveOrgasmBuild(Pleasure: any, Bonus: any, Intensity: any): void;
declare function SarahSlaveReset(): void;
declare var SarahRoomAvailable: boolean;
declare var SarahBackground: string;
declare var SarahStatus: string;
declare var AmandaStatus: string;
declare var SophieStatus: string;
declare var Sarah: any;
declare var Amanda: any;
declare var Sophie: any;
declare var SarahInside: boolean;
declare var AmandaInside: boolean;
declare var SophieInside: boolean;
declare var SarahUnlockQuest: boolean;
declare var SarahCharacter: any[];
declare var SophieUpsetCount: number;
declare var SophieFightDone: boolean;
declare var SophiePunishmentStage: number;
declare var SophieOrgasmGameCount: number;
declare var SophieOrgasmGamePleasure: number;
