declare function CollegeCafeteriaSidneyStatusIs(QueryStatus: any): boolean;
declare function CollegeCafeteriaCanInviteToPrivateRoom(): boolean;
declare function CollegeCafeteriaLoad(): void;
declare function CollegeCafeteriaRun(): void;
declare function CollegeCafeteriaClick(): void;
declare function CollegeCafeteriaSidneyLoveChange(LoveChange: any, MoneyChange: any): void;
declare function CollegeCafeteriaFightStart(): void;
declare function CollegeCafeteriaFightEnd(): void;
declare function CollegeCafeteriaInviteToPrivateRoom(): void;
declare var CollegeCafeteriaBackground: string;
declare var CollegeCafeteriaSidney: any;
declare var CollegeCafeteriaSidneyStatus: string;
declare var CollegeCafeteriaSidneyLove: number;
declare var CollegeCafeteriaStudentRight: any;
declare var CollegeCafeteriaStudentFarRight: any;
