declare function PrivateIsCaged(): boolean;
declare function PrivateVendorCanPlay(): any;
declare function PrivateAllowChange(): boolean;
declare function PrivateWontChange(): boolean;
declare function PrivateIsRestrained(): any;
declare function PrivateAllowRestain(): any;
declare function PrivateNobodyGagged(): any;
declare function PrivateCanMasturbate(): boolean;
declare function PrivateCanFondle(): boolean;
declare function PrivateAllowRestainPlayer(): boolean;
declare function PrivateWontRestainPlayer(): boolean;
declare function PrivateAllowReleasePlayer(): boolean;
declare function PrivateWontReleasePlayer(): boolean;
declare function PrivateWontReleasePlayerOwner(): boolean;
declare function PrivateWontReleasePlayerOwnerOnly(): any;
declare function PrivateWillKneel(): any;
declare function PrivateWillKneelGagged(): any;
declare function PrivateWontKneel(): boolean;
declare function PrivateCannotKneel(): boolean;
declare function PrivateCanStandUp(): any;
declare function PrivateCanStandUpGagged(): any;
declare function PrivateCannotStandUp(): any;
declare function PrivateWouldTakePlayerAsSub(): boolean;
declare function PrivateWontTakePlayerAsSub(): boolean;
declare function PrivateNeedTimeToTakePlayerAsSub(): boolean;
declare function PrivateNeverTakePlayerAsSub(): boolean;
declare function PrivateTrialInProgress(): boolean;
declare function PrivateTrialDoneEnoughLove(): boolean;
declare function PrivateTrialDoneNotEnoughLove(): boolean;
declare function PrivateTrialCanCancel(): boolean;
declare function PrivateWillForgive(): boolean;
declare function PrivateCanAskUncollar(): boolean;
declare function PrivateCannotAskUncollar(): boolean;
declare function PrivateIsMistress(): boolean;
declare function PrivateWouldTakePlayerAsDom(): boolean;
declare function PrivateWontTakePlayerAsDom(): boolean;
declare function PrivateNeedTimeToTakePlayerAsDom(): boolean;
declare function PrivateNeverTakePlayerAsDom(): boolean;
declare function PrivateIsHappy(): boolean;
declare function PrivateIsUnhappy(): boolean;
declare function PrivateIsNeutral(): boolean;
declare function PrivateIsLoverHappy(): any;
declare function PrivateIsLoverUnhappy(): any;
declare function PrivateIsLoverNeutral(): any;
declare function PrivateSubTrialInProgress(): boolean;
declare function PrivateSubTrialOverWilling(): boolean;
declare function PrivateSubTrialOverUnwilling(): boolean;
declare function PrivateCanPet(): boolean;
declare function PrivateCanSellSlave(): boolean;
declare function PrivateCannotSellSlave(): boolean;
declare function PrivateCanGetCollegeClothes(): boolean;
declare function PrivateIsLover(): any;
declare function PrivateWillTakePlayerAsLover(): boolean;
declare function PrivateWontTakePlayerAsLover(): boolean;
declare function PrivateWontTakePlayerAsLoverAlreadyDating(): boolean;
declare function PrivateWontTakePlayerAsLoverPlayerDating(): boolean;
declare function PrivateLoad(): void;
declare function PrivateExpansionLoad(): void;
declare function PrivateDrawCharacter(): void;
declare function PrivateRun(): void;
declare function PrivateClickCharacterButton(): void;
declare function PrivateClickCharacter(): void;
declare function PrivateClick(): void;
declare function PrivateSetCharacterOffset(O: any): void;
declare function PrivateRentRoom(): void;
declare function PrivateGetWardrobe(): void;
declare function PrivateGetCage(): void;
declare function PrivateGetExpansion(): void;
declare function PrivateLoadCharacter(C: any): void;
declare function PrivateAddCharacter(Template: any, Archetype: any, CustomData: any): void;
declare function PrivateGetCurrentID(): number;
declare function PrivateKickOut(): void;
declare function PrivateChange(NewCloth: any): void;
declare function PrivateOwnerInRoom(): boolean;
declare function PrivateLoverInRoom(L: any): boolean;
declare function PrivateRestrainPlayer(): void;
declare function PrivateRelationDecay(): void;
declare function PrivateStartTrial(ChangeRep: any): void;
declare function PrivateStopTrial(ChangeRep: any): void;
declare function PrivateShowTrialHours(): void;
declare function PrivatePlayerIsOwned(): boolean;
declare function PrivateCanRestrainOther(): boolean;
declare function PrivateStartActivity(): void;
declare function PrivateActivityRun(LoveFactor: any): void;
declare function PrivateBlockChange(Minutes: any): void;
declare function PrivateSelectPunishment(): void;
declare function PrivateRunPunishment(LoveFactor: any): void;
declare function PrivatePlayerCollaring(): void;
declare function PrivateStartDomTrial(TrialTime: any): void;
declare function PrivateNPCCollaring(): void;
declare function PrivateStartGirlfriend(): void;
declare function PrivateNPCInteraction(LoveFactor: any): void;
declare function PrivateSlaveMarketStart(AuctionType: any): void;
declare function PrivateSlaveImproveSelect(Type: any): void;
declare function PrivateSlaveImproveSend(): void;
declare function PrivateGetCollegeClothes(): void;
declare function PrivateLoveYou(): void;
declare var PrivateBackground: string;
declare var PrivateVendor: any;
declare var PrivateCharacter: any[];
declare var PrivateCharacterOffset: number;
declare var PrivateCharacterTypeList: string[];
declare var PrivateCharacterToSave: number;
declare var PrivateCharacterMax: number;
declare var PrivateReleaseTimer: number;
declare var PrivateActivity: string;
declare var PrivateActivityCount: number;
declare var PrivateActivityAffectLove: boolean;
declare var PrivateActivityList: string[];
declare var PrivateActivityTarget: any;
declare var PrivatePunishment: string;
declare var PrivatePunishmentList: string[];
declare var PrivateCharacterNewClothes: any;
declare var PrivateSlaveImproveType: string;
declare var PrivateNextLoveYou: number;
declare var PrivateLoverActivity: string;
declare var PrivateLoverActivityList: string[];
declare var PrivateBeltList: string[];
