declare function OnlneGameDictionaryLoad(): void;
declare function OnlineGameDictionaryText(KeyWord: any): any;
declare function OnlineGameClickCharacter(C: any): boolean;
declare function OnlineGameClick(): boolean;
declare function OnlineGameRun(): void;
declare function OnlineGameAllowChange(): boolean;
declare function OnlineGameAllowBlockItems(): boolean;
declare function OnlineGameLoadStatus(): void;
declare function OnlineGameDrawCharacter(C: any, X: any, Y: any, Zoom: any): void;
declare var OnlineGameName: string;
declare var OnlineGameDictionary: any;
