declare function PhotographicPlayerCanChangeCloth(): boolean;
declare function PhotographicPlayerHatAvailable(): boolean;
declare function PhotographicPlayerGlovesAvailable(): boolean;
declare function PhotographicPlayerClothAvailable(): boolean;
declare function PhotographicPlayerClothLowerAvailable(): boolean;
declare function PhotographicPlayerShoesAvailable(): boolean;
declare function PhotographicPlayerSocksAvailable(): boolean;
declare function PhotographicPlayerBraAvailable(): boolean;
declare function PhotographicPlayerPantiesAvailable(): boolean;
declare function PhotographicSubIsRestrained(): any;
declare function PhotographicSubHatAvailable(): boolean;
declare function PhotographicSubGlovesAvailable(): boolean;
declare function PhotographicSubClothAvailable(): boolean;
declare function PhotographicSubClothLowerAvailable(): boolean;
declare function PhotographicSubShoesAvailable(): boolean;
declare function PhotographicSubSocksAvailable(): boolean;
declare function PhotographicSubBraAvailable(): boolean;
declare function PhotographicSubPantiesAvailable(): boolean;
declare function PhotographicSubCanAskForPhoto(): boolean;
declare function PhotographicSubCanWinkForPhoto(): boolean;
declare function PhotographicSubCanKeel(): any;
declare function PhotographicIsRestrainedWithLock(): boolean;
declare function PhotographicIsRestrainedWithoutLock(): boolean;
declare function PhotographicLoad(): void;
declare function PhotographicRun(): void;
declare function PhotographicClick(): void;
declare function PhotographicCanvasToPng(x: any): void;
declare function PhotographicShotThePlayerPhoto(): void;
declare function PhotographicPlayerClothRemove(Group: any): void;
declare function PhotographicAppearanceAvailable(C: any, Group: any): boolean;
declare function PhotographicPlayerAssetAvailable(Asset: any, Group: any): boolean;
declare function PhotographicPlayerRelease(): void;
declare function PhotographicUseAsset(Asset: any, Group: any): void;
declare function PhotographicPlayerDressBack(): void;
declare function PhotographicSubDressBack(): void;
declare function PhotographicSubChangePose(): void;
declare function PhotographicSubClothRemove(Group: any): void;
declare function PhotographicStartInventoryPlayer(ItemGroup: any): void;
declare var PhotographicBackground: string;
declare var PhotographicSub: any;
declare var PhotographicGroupStarted: boolean;
declare var PhotographicCurrendGroup: any;
declare var PhotographicSubAppearance: any;
declare var PhotographicSelectText: string;
