declare function CafeMaidCanServe(): boolean;
declare function CafeMaidCannotServe(): any;
declare function CafePlayerCannotConsume(): any;
declare function CafeOnlineDrinkCompleted(): boolean;
declare function CafeIsGaggedHeadMaid(): boolean;
declare function CafeIsGaggedSeniorMaid(): boolean;
declare function CafeIsGaggedMaid(): boolean;
declare function CafeIsMaidChoice(): boolean;
declare function CafeIsMaidNoChoice(): boolean;
declare function CafeCanDildo(): boolean;
declare function CafeEquired(Type: any): boolean;
declare function CafeLoad(): void;
declare function CafeRun(): void;
declare function CafeClick(): void;
declare function CafeEquirePrice(Item: any): void;
declare function CafeConsumeSpeciiality(): void;
declare function CafeServiceBound(Style: any): void;
declare function CafeRamdomBound(): void;
declare function CafeRefillTray(): void;
declare function CafeGivenDildo(): void;
declare function CafeTurnDildoUp(): void;
declare var CafeBackground: string;
declare var CafeMaid: any;
declare var CafeIsMaid: boolean;
declare var CafeIsHeadMaid: boolean;
declare var CafeVibeIncreased: boolean;
declare var CafeEnergyDrinkPrice: number;
declare var CafeGlassMilkPrice: number;
declare var CafeCupcakePrice: number;
declare var CafeAskedFor: any;
declare var CafePrice: number;
