declare function KidnapLoadStats(C: any, Bonus: any): void;
declare function KidnapInventoryBuild(): void;
declare function KidnapSetMode(NewMode: any): void;
declare function KidnapAIMove(): number;
declare function KidnapUpperHandMoveAvailable(MoveType: any, DoMove: any): boolean;
declare function KidnapAIMoveUpperHand(): void;
declare function KidnapShowMove(): void;
declare function KidnapMoveEffective(C: any, MoveType: any): boolean;
declare function KidnapSelectMove(PlayerMove: any): void;
declare function KidnapSelectMoveUpperHand(PlayerMove: any): void;
declare function KidnapSurrender(): void;
declare function KidnapStart(Opponent: any, Background: any, Difficulty: any, ReturnFunction: any): void;
declare function KidnapDrawMove(C: any, Header: any, X: any): void;
declare function KidnapDrawMoveUpperHand(): void;
declare function KidnapShowTimer(): void;
declare function KidnapTitle(Title: any): void;
declare function KidnapShowItem(): void;
declare function KidnapRun(): void;
declare function KidnapClick(): void;
declare var KidnapVictory: boolean;
declare var KidnapDifficulty: number;
declare var KidnapBackground: string;
declare var KidnapReturnFunction: string;
declare var KidnapOpponent: any;
declare var KidnapPlayerCloth: any;
declare var KidnapPlayerClothAccessory: any;
declare var KidnapPlayerClothLower: any;
declare var KidnapOpponentCloth: any;
declare var KidnapOpponentClothAccessory: any;
declare var KidnapOpponentClothLower: any;
declare var KidnapTimer: number;
declare var KidnapMode: string;
declare var KidnapDialog: string;
declare var KidnapPlayerMove: string;
declare var KidnapOpponentMove: string;
declare var KidnapResultPlayer: string;
declare var KidnapResultOpponent: string;
declare var KidnapResultUpperHand: string;
declare var KidnapUpperHandVictim: any;
declare var KidnapUpperHandSelection: number;
declare var KidnapMoveType: string[];
declare var KidnapUpperHandMoveType: string[];
declare var KidnapMoveMap: number[][];
