declare function NPCCollaringLoad(): void;
declare function NPCCollaringRun(): void;
declare function NPCCollaringClick(): void;
declare var NPCCollaringBackground: string;
declare var NPCCollaringSub: any;
declare var NPCCollaringMistressLeft: any;
declare var NPCCollaringMistressRight: any;
declare var NPCCollaringGirlLeft: any;
declare var NPCCollaringGirlRight: any;
