declare function ShopIsVendorRestrained(): any;
declare function ShopIsRescueScenario(ScenarioName: any): boolean;
declare function ShopLoad(): void;
declare function ShopRun(): void;
declare function ShopAssetFocusGroup(Asset: any): boolean;
declare function ShopAssetMissing(Asset: any): boolean;
declare function ShopSelectAssetMissing(): void;
declare function ShopClick(): void;
declare function ShopStart(ItemGroup: any): void;
declare function ShopCompleteRescue(): void;
declare function ShopCheckBoughtEverything(): void;
declare function ShopVendorBondage(): void;
declare function ShopJobRestrain(): void;
declare function ShopJobStart(): void;
declare var ShopBackground: string;
declare var ShopVendor: any;
declare var ShopCustomer: any;
declare var ShopVendorAllowItem: boolean;
declare var ShopBoughtEverything: boolean;
declare var ShopStarted: boolean;
declare var ShopText: string;
declare var ShopRescueScenario: string;
declare var ShopRescueScenarioList: string[];
declare var ShopItemOffset: number;
declare var ShopItemCount: number;
declare var ShopDemoItemPayment: number;
declare var ShopDemoItemGroup: string;
declare var ShopDemoItemGroupList: string[];
declare function ShopSelectAsset(Asset: any): boolean;
