declare function PrisonPlayerIsHandcuffed(): boolean;
declare function PrisonPlayerIsPanelGag(): boolean;
declare function PrisonPlayerIsLegTied(): boolean;
declare function PrisonPlayerIsFeetTied(): boolean;
declare function PrisonPlayerIsOTMGag(): boolean;
declare function PrisonPlayerIsStriped(): boolean;
declare function PrisonPlayerIsBadGirl(): boolean;
declare function PrisonPlayerIsBadGirlThief(): boolean;
declare function PrisonPlayerHasSleepingPills(): boolean;
declare function PrisonPlayerHasSpankingToys(): boolean;
declare function PrisonPlayerHasKeys(): boolean;
declare function PrisonSubIsHandcuffedOut(): boolean;
declare function PrisonSubIsBehindBars(): boolean;
declare function PrisonSubIsFree(): boolean;
declare function PrisonSubAskForCuff(): boolean;
declare function PrisonSubCanStripSearch(): boolean;
declare function PrisonSubCanClothBack(): boolean;
declare function PrisonLoad(): void;
declare function PrisonRun(): void;
declare function PrisonClick(): void;
declare function PrisonCharacterAppearanceAvailable(C: any, AppearanceName: any, AppearanceGroup: any): boolean;
declare function PrisonCharacterAppearanceGroupAvailable(C: any, AppearanceGroup: any): boolean;
declare function PrisonCellPlayerIn(): void;
declare function PrisonCellPlayerOut(): void;
declare function PrisonMaidLeave(): void;
declare function PrisonCellRelease(C: any): void;
declare function PrisonHavySearch(C: any): void;
declare function PrisonLightSearch(C: any): void;
declare function PrisonerClothBack(C: any): void;
declare function PrisonCuffsRelief(): void;
declare function PrisonMaidLightTorture(): void;
declare function PrisonMaidHevyTorture(): void;
declare function PrisonDisableKey(C: any): void;
declare function PrisonCellPlayerAsk(): void;
declare function PrisonCellPlayerShake(): void;
declare function PrisonCellPlayerTry(): void;
declare function PrisonCellPlayerWimper(): void;
declare function PrisonCellPlayerWait(): void;
declare function PrisonSubSendAway(): void;
declare function PrisonSubHandcuffing(): void;
declare function PrisonCellSubIn(): void;
declare function PrisonSubHavySearch(): void;
declare function PrisonCellSubOut(): void;
declare function PrisonLeaveCell(): void;
declare function PrisonSubClothBack(): void;
declare function PrisonBecomeBadGirl(): void;
declare function PrisonLeaveBadGirl(): void;
declare function PrisonWearPoliceEquipment(C: any): void;
declare function PrisonWantedPlayer(): 1 | 4 | 7;
declare function PrisonMeetPoliceIntro(RoomBackground: any): void;
declare function PrisonFightPolice(): void;
declare function PrisonFightPoliceEnd(): void;
declare function PrisonFightPoliceOutro(): void;
declare function PrisonCatchByPolice(): void;
declare function PrisonSetBehavior(Behavior: any): void;
declare function PrisonArrestHandoverDices(): void;
declare function PrisonArrestHandoverKeys(): void;
declare function PrisonArrestHandoverSleepingPills(): void;
declare function PrisonArrestHandoverSpankingToys(): void;
declare function PrisonArrestStripOuterCloth(): void;
declare function PrisonCharacterIsInUnderwear(): boolean;
declare function PrisonArrestStripUnderware(): void;
declare function PrisonArrestSuit(): void;
declare function PrisonArrestShackle(): void;
declare function PrisonArrestEquipmentSearch(): void;
declare function PrisonArrestConfiscatDices(): void;
declare function PrisonArrestConfiscatKeys(): void;
declare function PrisonArrestConfiscatSleepingPills(): void;
declare function PrisonArrestConfiscatSpankingToys(): void;
declare function PrisonArrestLeave(): void;
declare function PrisonDiceBack(): void;
declare var PrisonBackground: string;
declare var PrisonNextEventTimer: any;
declare var PrisonNextEvent: boolean;
declare var PrisonerMetalCuffsKey: any;
declare var PrisonerMetalPadlockKey: any;
declare var PrisonerIntricatePadlockKey: any;
declare var PrisonerSleepingPills: any;
declare var PrisonerSpankingToys: any;
declare var PrisonBehavior: number;
declare var PrisonMaid: any;
declare var PrisonMaidAppearance: any;
declare var PrisonMaidIsPresent: boolean;
declare var PrisonMaidIsAngry: boolean;
declare var PrisonMaidCharacter: any;
declare var PrisonMaidCharacterList: string[];
declare var PrisonMaidChaotic: any;
declare var PrisonSub: any;
declare var PrisonSubAppearance: any;
declare var PrisonSubBehindBars: boolean;
declare var PrisonSubSelfCuffed: boolean;
declare var PrisonSubIsPresent: boolean;
declare var PrisonSubAskedCuff: boolean;
declare var PrisonSubIsLeaveOut: boolean;
declare var PrisonSubIsStripSearch: boolean;
declare var PrisonPolice: any;
declare var PrisonPoliceIsPresent: boolean;
declare var PrisonPlayerCatchedBadGirl: boolean;
declare var PrisonPlayerAppearance: any;
declare var PrisonPlayerBehindBars: boolean;
declare var PrisonPlayerForIllegalChange: boolean;
