declare function MaidQuartersPlayerInMaidUniform(): boolean;
declare function MaidQuartersAllowMaidDrinks(): boolean;
declare function MaidQuartersAllowMaidCleaning(): boolean;
declare function MaidQuartersAllowMaidPlayMusic(): boolean;
declare function MaidQuartersAllowRescue(): boolean;
declare function MaidQuartersAllowCancelRescue(): boolean;
declare function MaidQuartersCanFreeSarah(): boolean;
declare function MaidQuartersCanReleasePlayer(): any;
declare function MaidQuartersCannotReleasePlayer(): boolean;
declare function MaidQuartersCanGetDusterGag(): boolean;
declare function MaidQuartersOnlineDrinkCompleted(): boolean;
declare function MaidQuartersCanUngag(): boolean;
declare function MaidQuartersCannotUngag(): boolean;
declare function MaidQuartersLoad(): void;
declare function MaidQuartersRun(): void;
declare function MaidQuartersClick(): void;
declare function MaidQuartersMaidUngagPlayer(): void;
declare function MaidQuartersWearMaidUniform(): void;
declare function MaidQuartersRemoveMaidUniform(): void;
declare function MaidQuartersMiniGameStart(GameType: any, Difficulty: any): void;
declare function MaidQuartersMiniGameEnd(): void;
declare function MaidQuartersMiniGamePay(): void;
declare function MaidQuartersMiniGamePayAdvanced(): void;
declare function MaidQuartersRescuePay(): void;
declare function MaidQuartersMaidReleasePlayer(): void;
declare function MaidQuartersDominantRepChange(Value: any): void;
declare function MaidQuartersInitiationTransition(MaidType: any): void;
declare function MaidQuartersChangeInitiationMaid(): void;
declare function MaidQuartersBecomMaid(): void;
declare function MaidQuartersBecomHeadMaid(): void;
declare function MaidQuartersStartRescue(): void;
declare function MaidQuartersCancelRescue(): void;
declare function MaidQuartersFreeSarah(): void;
declare function MaidQuartersGetDusterGag(): void;
declare function MaidQuartersOnlineDrinkStart(): void;
declare function MaidQuartersOnlineDrinkPick(MemberNumber: any, DrinkValue: any): void;
declare function MaidQuartersOnlineDrinkPay(): void;
declare function MaidQuartersNotFromOwner(): void;
declare var MaidQuartersBackground: string;
declare var MaidQuartersMaid: any;
declare var MaidQuartersMaidInitiation: any;
declare namespace MaidQuartersItemClothPrev {
    const Cloth: any;
    const Hat: any;
    const ItemArms: any;
    const ItemLegs: any;
    const ItemFeet: any;
}
declare var MaidQuartersMaidReleasedPlayer: boolean;
declare var MaidQuartersCanBecomeMaid: boolean;
declare var MaidQuartersCannotBecomeMaidYet: boolean;
declare var MaidQuartersCanBecomeHeadMaid: boolean;
declare var MaidQuartersCannotBecomeHeadMaidYet: boolean;
declare var MaidQuartersIsMaid: boolean;
declare var MaidQuartersIsHeadMaid: boolean;
declare var MaidQuartersDominantRep: number;
declare var MaidQuartersCurrentRescue: string;
declare var MaidQuartersRescueList: string[];
declare var MaidQuartersRescueStage: string[];
declare var MaidQuartersCurrentRescueStarted: boolean;
declare var MaidQuartersCurrentRescueCompleted: boolean;
declare var MaidQuartersOnlineDrinkCount: number;
declare var MaidQuartersOnlineDrinkValue: number;
declare var MaidQuartersOnlineDrinkCustomer: any[];
declare var MaidQuartersOnlineDrinkFromOwner: boolean;
