declare function CollegeTennisJenniferStatusIs(QueryStatus: any): boolean;
declare function CollegeTennisCanInviteToPrivateRoom(): boolean;
declare function CollegeTennisLoad(): void;
declare function CollegeTennisRun(): void;
declare function CollegeTennisClick(): void;
declare function CollegeTennisGameStart(Difficulty: any): void;
declare function CollegeTennisGameEnd(): void;
declare function CollegeTennisInviteToPrivateRoom(): void;
declare var CollegeTennisBackground: string;
declare var CollegeTennisJennifer: any;
declare var CollegeTennisJenniferStatus: string;
declare var CollegeTennisJenniferWillJoinRoom: boolean;
