declare function ShibariAllowTeacherBondage(): boolean;
declare function ShibariAllowTeacherStrip(): any;
declare function ShibariAllowPlayerBondage(): boolean;
declare function ShibariAllowSpank(): any;
declare function ShibariIsRescueScenario(ScenarioName: any): boolean;
declare function ShibariIsTeacherRestrained(): any;
declare function ShibariCanTrainSkill(SkillType: any): boolean;
declare function ShibariCanPayForTraining(): boolean;
declare function ShibariRandomBondage(C: any, Level: any): void;
declare function ShibariLoad(): void;
declare function ShibariRun(): void;
declare function ShibariClick(): void;
declare function ShibariStartTeacherBondage(): void;
declare function ShibariRestrainPlayer(Level: any): void;
declare function ShibariSubComment(): void;
declare function ShibariDomComment(): void;
declare function ShibariSurrenderToTeacher(): void;
declare function ShibariSpank(): void;
declare function ShibariGetRope(): void;
declare function ShibariCompleteRescue(): void;
declare function ShibariCalculateTrainingPrice(SkillType: any): void;
declare function ShibariPayForTraining(SkillType: any): void;
declare var ShibariBackground: string;
declare var ShibariTeacher: any;
declare var ShibariTeacherAppearance: any;
declare var ShibariAllowTeacherItem: boolean;
declare var ShibariStudent: any;
declare var ShibariPlayerAppearance: any;
declare var ShibariSubCommentDone: boolean;
declare var ShibariDomCommentDone: boolean;
declare var ShibariSurrenderDone: boolean;
declare var ShibariSpankDone: boolean;
declare var ShibariTeacherReleaseTimer: boolean;
declare var ShibariRescueScenario: string;
declare var ShibariRescueScenarioList: string[];
declare var ShibariTrainingPrice: number;
declare var ShibariTrainingPriceList: number[];
