declare function GamblingIsSubsRestrained(): any;
declare function GamblingFirstSubRestrained(): any;
declare function GamblingFirstCanPlay(): any;
declare function GamblingSecondSubRestrained(): any;
declare function GamblingSecondCanPlay(): any;
declare function GamblingCanPlaySimpleDice(): any;
declare function GamblingCanPlayTwentyOne(): boolean;
declare function GamblingCanPlayToothpick(): boolean;
declare function GamblingCanPlayFox(): boolean;
declare function GamblingCanPlayStreetRoissy(): boolean;
declare function GamblingCanPlayDaredSix(): boolean;
declare function GamblingToothpickCanPickOne(): boolean;
declare function GamblingToothpickCanPickTwo(): boolean;
declare function GamblingToothpickCanPickThree(): boolean;
declare function GamblingIsRestrainedWithLock(): boolean;
declare function GamblingIsRestrainedWithoutLock(): boolean;
declare function GamblingCanPayToRelease(): boolean;
declare function GamblingCannotPayToRelease(): boolean;
declare function GamblingCanStealDice(): boolean;
declare function GamblingLoad(): void;
declare function GamblingRun(): void;
declare function GamblingClick(): void;
declare function GamblingShowDiceStack(): boolean;
declare function GamblingShowNpcDice(): boolean;
declare function GamblingDiceStackSum(DiceStack: any): number;
declare function GamblingSimpleDiceController(SimpleDiceState: any): void;
declare function GamblingShowToothpickStack(): boolean;
declare function GamblingToothpickController(ToothpickState: any): void;
declare function GamblingToothpickNPCChoice(): number;
declare function GamblingTwentyOneController(TwentyOneState: any): void;
declare function GamblingFoxController(FoxState: any): void;
declare function GamblingStreetRoissyController(StreetRoissyState: any): void;
declare function GamblingDaredSixController(DaredSixState: any): void;
declare function GamblingDressingLevel(C: any): 1 | 3 | 0 | 2;
declare function GamblingStripTied(gstCarachter: any, gstLevel: any): boolean;
declare function GamblingAnnoyGamblingFirstSub(): void;
declare function GamblingReleasePlayerGame(ReleaseState: any): void;
declare function GamblingPayForFreedom(): void;
declare function GamblingDressBackPlayer(): void;
declare function GamblingCompleteRescue(): void;
declare function GamblingStealDice(): void;
declare var GamblingBackground: string;
declare var GamblingFirstSub: any;
declare var GamblingSecondSub: any;
declare var GamblingPlayerDice: any;
declare var GamblingPolice: any;
declare var GamblingNpcDice: any;
declare var GamblingPlayerDiceStack: any[];
declare var GamblingNpcDiceStack: any[];
declare var GamblingPlayerSubState: number;
declare var GamblingNpcSubState: number;
declare var GamblingPlayerIsFox: boolean;
declare var GamblingMoneyBet: number;
declare var GamblingShowDiceSum: boolean;
declare var GamblingShowMoney: boolean;
declare var GamblingAppearanceFirst: any;
declare var GamblingAppearanceSecond: any;
declare var GamblingAppearancePlayer: any;
declare var GamblingIllegalChange: boolean;
declare var GamblingToothpickCount: number;
