declare function PlayerCollaringLoad(): void;
declare function PlayerCollaringRun(): void;
declare function PlayerCollaringClick(): void;
declare var PlayerCollaringBackground: string;
declare var PlayerCollaringMistress: any;
declare var PlayerCollaringMistressLeft: any;
declare var PlayerCollaringMistressRight: any;
declare var PlayerCollaringGirlLeft: any;
declare var PlayerCollaringGirlRight: any;
