declare function GameLARPIsAdmin(C: any): boolean;
declare function GameLARPDrawIcon(C: any, X: any, Y: any, Zoom: any): void;
declare function GameLARPLoad(): void;
declare function GameLARPRun(): void;
declare function GameLARPRunProcess(): void;
declare function GameLARPBuildInventory(FocusGroup: any): void;
declare function GameLARPClickOption(Name: any): void;
declare function GameLARPClickProcess(): boolean;
declare function GameLARPClick(): void;
declare function GameLARPExit(): void;
declare function GameLARPCanLaunchGame(): boolean;
declare function GameLARPGetBonus(Target: any, BonusType: any): number;
declare function GameLARPGetOdds(Action: any, Source: any, Target: any): string | 1 | 0;
declare function GameLARPCanTalk(C: any): boolean;
declare function GameLARPCanWalk(C: any): boolean;
declare function GameLARPCanAct(C: any): boolean;
declare function GameLARPClothed(C: any): boolean;
declare function GameLARPCanRemoveItem(C: any, Zone: any): boolean;
declare function GameLARPBuildOptionAbility(Source: any, Target: any, Option: any, Ability: any): void;
declare function GameLARPBuildOption(Source: any, Target: any): {
    Name: string;
    Odds: string | number;
}[];
declare function GameLARPGetPlayer(MemberNumber: any): any;
declare function GameLARPProcessAction(Action: any, ItemName: any, Source: any, Target: any, RNG: any): void;
declare function GameLARPCharacterClick(C: any): boolean;
declare function GameLARPAddChatLog(Msg: any, Source: any, Target: any, Description: any, RNG: any, Odds: any, Color: any): void;
declare function GameLARPNewTurnPublish(NewPlayerPosition: any, Ascending: any, Msg: any): void;
declare function GameLARPNewTurn(Msg: any): void;
declare function GameLARPBuildPlayerList(): void;
declare function GameLARPContinue(): boolean;
declare function GameLARPProcess(P: any): void;
declare var GameLARPBackground: string;
declare var GameLARPClass: {
    Name: string;
    Bonus: number[];
    Ability: string[];
}[];
declare var GameLARPTeamList: string[];
declare var GameLARPEntryClass: string;
declare var GameLARPEntryTeam: string;
declare var GameLARPStatus: string;
declare var GameLARPProgress: any[];
declare var GameLARPPlayer: any[];
declare var GameLARPOption: any[];
declare var GameLARPAction: string;
declare var GameLARPInventory: any[];
declare var GameLARPInventoryOffset: number;
declare var GameLARPTurnAdmin: number;
declare var GameLARPTurnPosition: number;
declare var GameLARPTurnAscending: boolean;
declare var GameLARPTurnTimer: any;
declare var GameLARPTurnFocusCharacter: any;
declare var GameLARPTurnFocusGroup: any;
