declare function CollegeDetentionCanInviteToPrivateRoom(): boolean;
declare function CollegeDetentionYukiLoveIs(LoveLevel: any): boolean;
declare function CollegeDetentionGetSleepingPills(): void;
declare function CollegeDetentionGetTeacherKey(): void;
declare function CollegeDetentionYukiWillRelease(): boolean;
declare function CollegeDetentionYukiClothes(): void;
declare function CollegeDetentionLoad(): void;
declare function CollegeDetentionRun(): void;
declare function CollegeDetentionClick(): void;
declare function CollegeDetentionYukiLoveChange(LoveChange: any, Event: any): void;
declare function CollegeDetentionDressBack(): void;
declare function CollegeDetentionBothNaked(): void;
declare function CollegeDetentionPleaseYuki(Factor: any): void;
declare function CollegeDetentionRestrainPlayer(Type: any): void;
declare function CollegeDetentionInviteToPrivateRoom(): void;
declare var CollegeDetentionBackground: string;
declare var CollegeDetentionYuki: any;
declare var CollegeDetentionYukiLove: number;
declare var CollegeDetentionYukiWillReleaseAt: number;
