declare function KidnapLeagueAllowKidnap(): boolean;
declare function KidnapLeagueIsTrainerRestrained(): any;
declare function KidnapLeagueCanTakeBounty(): boolean;
declare function KidnapLeagueBountyTaken(): boolean;
declare function KidnapLeagueBountyWasVictory(): boolean;
declare function KidnapLeagueBountyWasDefeat(): boolean;
declare function KidnapLeagueCanTransferToRoom(): boolean;
declare function KidnapLeagueWontVisitRoom(): boolean;
declare function KidnapLeagueCanKiss(): any;
declare function KidnapLeagueLoad(): void;
declare function KidnapLeagueRun(): void;
declare function KidnapLeagueClick(): void;
declare function KidnapLeagueTakeBounty(Difficulty: any): void;
declare function KidnapLeagueBountyRemind(): void;
declare function KidnapLeagueBountyStart(): void;
declare function KidnapLeagueBountyFightStart(): void;
declare function KidnapLeagueBountyFightEnd(): void;
declare function KidnapLeagueBountyPay(): void;
declare function KidnapLeagueBountyReset(): void;
declare function KidnapLeagueStartKidnap(Difficulty: any): void;
declare function KidnapLeagueEndKidnap(): void;
declare function KidnapLeagueResetTrainer(): void;
declare function KidnapLeagueRandomIntro(): void;
declare function KidnapLeagueRandomOutro(Surrender: any): void;
declare function KidnapLeagueRandomStart(): void;
declare function KidnapLeagueRandomBribe(Amount: any): void;
declare function KidnapLeagueRandomSurrender(): void;
declare function KidnapLeagueRandomEnd(): void;
declare function KidnapLeagueRandomMoneyAmount(): void;
declare function KidnapLeagueRandomEndMoney(): void;
declare function KidnapLeagueRandomActivityStart(A: any): void;
declare function KidnapLeagueRandomActivityLaunch(): void;
declare function KidnapLeagueTransferToRoom(): void;
declare var KidnapLeagueBackground: string;
declare var KidnapLeagueTrainer: any;
declare var KidnapLeagueRandomKidnapper: any;
declare var KidnapLeagueRandomKidnapperScenario: string;
declare var KidnapLeagueRandomKidnapperDifficulty: number;
declare var KidnapLeagueArchetype: any;
declare var KidnapLeagueWillPayForFreedom: boolean;
declare var KidnapLeagueRandomActivityList: string[];
declare var KidnapLeagueRandomActivity: string;
declare var KidnapLeagueRandomActivityCount: number;
declare var KidnapLeagueBounty: any;
declare var KidnapLeagueBountyDifficulty: any;
declare var KidnapLeagueBountyLocation: string;
declare var KidnapLeagueBountyLocationList: string[];
declare var KidnapLeagueBountyVictory: any;
declare var KidnapLeagueVisitRoom: boolean;
