declare function CollegeTeacherCanInviteToPrivateRoom(): boolean;
declare function CollegeTeacherMildredLoveIs(LoveLevel: any): boolean;
declare function CollegeTeacherMildredClothes(): void;
declare function CollegeTeacherLoad(): void;
declare function CollegeTeacherRun(): void;
declare function CollegeTeacherClick(): void;
declare function CollegeTeacherMildredLoveChange(LoveChange: any, Event: any): void;
declare function CollegeTeacherDressBack(): void;
declare function CollegeTeacherNewBackground(New: any): void;
declare function CollegeTeacherInviteToPrivateRoom(): void;
declare var CollegeTeacherBackground: string;
declare var CollegeTeacherMildred: any;
declare var CollegeTeacherMildredLove: number;
