declare function BackgroundSelectionMake(List: any, Idx: any, Callback: any): void;
declare function BackgroundSelectionLoad(): void;
declare function BackgroundSelectionInputChanged(): void;
declare function BackgroundSelectionRun(): void;
declare function BackgroundSelectionClick(): void;
declare function BackgroundSelectionKeyDown(): void;
declare function BackgroundSelectionExit(SetBackground: any): void;
declare var BackgroundSelectionBackground: string;
declare var BackgroundSelectionList: any[];
declare var BackgroundSelectionIndex: number;
declare var BackgroundSelectionSelect: string;
declare var BackgroundSelectionSelectName: string;
declare var BackgroundSelectionSize: number;
declare var BackgroundSelectionOffset: number;
declare var BackgroundSelectionCallback: number;
declare var BackgroundSelectionPreviousModule: string;
declare var BackgroundSelectionPreviousScreen: string;
declare var BackgroundSelectionAll: any[];
declare var BackgroundSelectionView: any[];
