declare function MaidDrinksGenerateMove(StartTime: any): void;
declare function MaidDrinksLoad(): void;
declare function MaidDrinksDrawIcons(): void;
declare function MaidDrinksDrawBar(SquareType: any): void;
declare function MaidDrinksCustomers(): void;
declare function MaidDrinksRun(): void;
declare function MaidDrinksEnd(Victory: any): void;
declare function MaidDrinksHit(): void;
declare function MaidDrinksMiss(): void;
declare function MaidDrinksDoMove(MoveType: any): void;
declare function MaidDrinksKeyDown(): void;
declare function MaidDrinksClick(): void;
declare var MaidDrinksBackground: string;
declare var MaidDrinksCustomerLeft: any;
declare var MaidDrinksCustomerRight: any;
declare var MaidDrinksCustomerLeftTimer: number;
declare var MaidDrinksCustomerRightTimer: number;
declare var MaidDrinksCustomerLeftVisible: boolean;
declare var MaidDrinksCustomerRightVisible: boolean;
declare var MaidDrinksMaxSequence: number;
declare var MaidDrinksMove: any[];
declare var MaidDrinksLastMoveType: number;
declare var MaidDrinksLastMoveTypeTimer: number;
declare var MaidDrinksKeyUpper: number[];
declare var MaidDrinksKeyLower: number[];
