declare function MagicShowIsState(QState: any): boolean;
declare function MagicAssistantIsReleased(): boolean;
declare function MagicRestrainPerformerMinItem(MinItem: any): boolean;
declare function MagicRestrainAssistantMinItem(MinItem: any): boolean;
declare function MagicAssistantIsDressRestrain(): any;
declare function MagicAssistantIsntDressRestrain(): boolean;
declare function MagicRestrainMinItem(C: any, MinItem: any): boolean;
declare function MagicLoad(): void;
declare function MagicRun(): void;
declare function MagicClick(): void;
declare function MagicTrickChangeDresses(): void;
declare function MagicTrickChangeDressesBack(): void;
declare function MagicAssistantDress(): void;
declare function MagicShowStart(): void;
declare function MagicShowIncomeAdd(): void;
declare function MagicShowPayoff(): void;
declare function MagicSelectTrick(): void;
declare function MagicTrickChangeBinds(): void;
declare function MagicTrickBindAsstant(): void;
declare function MagicTrickBoxTiedLight(): void;
declare function MagicTrickBoxTiedHeavy(): void;
declare function MagicTrickBoxMilkCan(): void;
declare function MagicTrickBoxWaterCell(): void;
declare function MagicTrickGetCoin(): void;
declare function MagicSongLeavePerformer(): void;
declare function MagicSongGwendoyn(): void;
declare function MagicSongBadGirl(): void;
declare function MagicAssistantRelese(): void;
declare function MagicTrickAsstantChange(): void;
declare function MagicTrickEndPerformance(): void;
declare function MagicRestrainCopyTransfer(FromC: any, ToC: any): void;
declare var MagicBackground: string;
declare var MagicPerformer: any;
declare var MagicPerformerAppearance: any;
declare var MagicAssistant: any;
declare var MagicAssistantAppearance: any;
declare var MagicPlayerAppearance: any;
declare var MagicTrick: any;
declare var MagicTrickList: string[];
declare var MagicTrickCounter: number;
declare var MagicShowIncome: number;
declare var MagicShowState: number;
