declare function CollegeEntranceCanGoTennis(): boolean;
declare function CollegeEntranceCanGoInside(): boolean;
declare function CollegeEntranceCanGoDetention(): boolean;
declare function CollegeEntranceCanGoTeacher(): boolean;
declare function CollegeEntranceLoad(): void;
declare function CollegeEntranceRun(): void;
declare function CollegeEntranceClick(): void;
declare function CollegeEntranceWearStudentClothes(C: any): void;
declare function CollegeEntranceIsWearingTennisClothes(): boolean;
declare function CollegeEntranceIsWearingCollegeClothes(): boolean;
declare var CollegeEntranceBackground: string;
declare var CollegeEntranceStudent: any;
