declare function ChatRoomCanAddWhiteList(): boolean;
declare function ChatRoomCanAddBlackList(): boolean;
declare function ChatRoomCanRemoveWhiteList(): boolean;
declare function ChatRoomCanRemoveBlackList(): boolean;
declare function ChatRoomCanAddFriend(): boolean;
declare function ChatRoomCanRemoveFriend(): boolean;
declare function ChatRoomCanAddGhost(): boolean;
declare function ChatRoomCanRemoveGhost(): boolean;
declare function ChatRoomCanChangeClothes(): boolean;
declare function ChatRoomOwnershipOptionIs(Option: any): boolean;
declare function ChatRoomLovershipOptionIs(Option: any): boolean;
declare function ChatRoomCanTakeDrink(): boolean;
declare function ChatRoomIsCollaredByPlayer(): boolean;
declare function ChatRoomCanServeDrink(): any;
declare function ChatRoomCanGiveMoneyForOwner(): boolean;
declare function ChatRoomPlayerIsAdmin(): boolean;
declare function ChatRoomCurrentCharacterIsAdmin(): boolean;
declare function ChatRoomHasSwapTarget(): boolean;
declare function ChatRoomCreateElement(): void;
declare function ChatRoomLoad(): void;
declare function ChatRoomStart(Space: any, Game: any, LeaveRoom: any, Background: any, BackgroundList: any): void;
declare function ChatRoomOwnerInside(): boolean;
declare function ChatRoomDrawCharacter(DoClick: any): void;
declare function ChatRoomCheckRelationships(): void;
declare function ChatRoomFirstTimeHelp(): void;
declare function ChatRoomTarget(): void;
declare function ChatRoomRun(): void;
declare function ChatRoomClick(): void;
declare function ChatRoomCanLeave(): boolean;
declare function ChatRoomKeyDown(): void;
declare function ChatRoomSendChat(): void;
declare function ChatRoomPublishAction(C: any, DialogProgressPrevItem: any, DialogProgressNextItem: any, LeaveDialog: any, Action?: any): void;
declare function ChatRoomCharacterItemUpdate(C: any, Group: any): void;
declare function ChatRoomPublishCustomAction(msg: any, LeaveDialog: any, Dictionary: any): void;
declare function ChatRoomCharacterUpdate(C: any): void;
declare function ChatRoomHTMLEntities(str: any): string;
declare function ChatRoomMessage(data: any): void;
declare function ChatRoomSync(data: any): void;
declare function ChatRoomSyncSingle(data: any): void;
declare function ChatRoomSyncExpression(data: any): void;
declare function ChatRoomSyncPose(data: any): void;
declare function ChatRoomSyncArousal(data: any): void;
declare function ChatRoomAllowChangeLockedItem(Data: any, Item: any): boolean;
declare function ChatRoomSyncItem(data: any): void;
declare function ChatRoomRefreshChatSettings(C: any): void;
declare function ChatRoomViewProfile(): void;
declare function ChatRoomAdminAction(ActionType: any, Publish: any): void;
declare function ChatRoomCompleteSwap(MemberNumber: any): void;
declare function ChatRoomAdminChatAction(ActionType: any, Message: any): void;
declare function ChatRoomCurrentTime(): string;
declare function ChatRoomGetTransparentColor(Color: any): string;
declare function ChatRoomListManage(Operation: any, ListType: any): void;
declare function ChatRoomListManipulation(Add: any, Remove: any, Message: any): void;
declare function ChatRoomAllowItem(data: any): void;
declare function ChatRoomChangeClothes(): void;
declare function ChatRoomSendOwnershipRequest(RequestType: any): void;
declare function ChatRoomSendLovershipRequest(RequestType: any): void;
declare function ChatRoomDrinkPick(DrinkType: any, Money: any): void;
declare function ChatRoomSendRule(RuleType: any, Option: any): void;
declare function ChatRoomSetRule(data: any): any;
declare function ChatRoomGiveMoneyForOwner(): void;
declare function ChatRoomPayQuest(data: any): void;
declare function ChatRoomGameResponse(data: any): void;
declare var ChatRoomBackground: string;
declare var ChatRoomData: {};
declare var ChatRoomCharacter: any[];
declare var ChatRoomLastMessage: string[];
declare var ChatRoomLastMessageIndex: number;
declare var ChatRoomTargetMemberNumber: any;
declare var ChatRoomOwnershipOption: string;
declare var ChatRoomLovershipOption: string;
declare var ChatRoomPlayerCanJoin: boolean;
declare var ChatRoomPlayerJoiningAsAdmin: boolean;
declare var ChatRoomMoneyForOwner: number;
declare var ChatRoomQuestGiven: any[];
declare var ChatRoomSpace: string;
declare var ChatRoomSwapTarget: any;
declare var ChatRoomHelpSeen: boolean;
declare var ChatRoomAllowCharacterUpdate: boolean;
