declare function CollegeTheaterCanInviteToPrivateRoom(): boolean;
declare function CollegeTheaterJuliaLoveIs(LoveLevel: any): boolean;
declare function CollegeTheaterCanChooseRole(): boolean;
declare function CollegeTheaterGetTeacherKey(): void;
declare function CollegeTheaterJuliaClothes(): void;
declare function CollegeTheaterLoad(): void;
declare function CollegeTheaterRun(): void;
declare function CollegeTheaterClick(): void;
declare function CollegeTheaterPlayClothes(C1: any, C2: any): void;
declare function CollegeTheaterRandomRope(C: any): void;
declare function CollegeTheaterRandomBelt(C: any): void;
declare function CollegeTheaterUnderwear(C: any): void;
declare function CollegeTheaterJuliaLoveChange(LoveChange: any, Event: any): void;
declare function CollegeTheaterDressBack(): void;
declare function CollegeTheaterInviteToPrivateRoom(Role: any): void;
declare var CollegeTheaterBackground: string;
declare var CollegeTheaterJulia: any;
declare var CollegeTheaterJuliaLove: number;
declare var CollegeTheaterRandomColors: string[];
