declare function IntroductionIsRescueScenario(ScenarioName: any): boolean;
declare function IntroductionIsBothFree(): any;
declare function IntroductionIsMaidRestrained(): any;
declare function IntroductionNoTitle(): boolean;
declare function IntroductionJobIsComplete(): boolean;
declare function IntroductionCanTakeJob(): boolean;
declare function IntroductionCannotTakeJobDone(): boolean;
declare function IntroductionCannotTakeJobRestrained(): boolean;
declare function IntroductionLoad(): void;
declare function IntroductionRun(): void;
declare function IntroductionClick(): void;
declare function IntroductionChangeMaidOpinion(Bonus: any): void;
declare function IntroductionSetZone(NewZone: any): void;
declare function IntroductionClearZone(): void;
declare function IntroductionGetBasicItems(): void;
declare function IntroductionSaveMaidOpinion(): void;
declare function IntroductionAllowRestrainPlayer(): any;
declare function IntroductionGagPlayer(): void;
declare function IntroductionCompleteRescue(): void;
declare function IntroductionJobDone(): void;
declare function IntroductionJobAvailable(JobName: any): boolean;
declare function IntroductionJobAnyAvailable(): boolean;
declare function IntroductionJobStart(JobName: any, JobCount: any): void;
declare function IntroductionJobGiveUp(): void;
declare function IntroductionJobLockType(): void;
declare function IntroductionJobProgress(JobName: any, Param: any, UniqueMember: any): void;
declare function IntroductionJobBouncerStart(): void;
declare function IntroductionJobPuppyStart(): void;
declare function IntroductionJobDojoStart(): void;
declare var IntroductionBackground: string;
declare var IntroductionMaid: any;
declare var IntroductionSub: any;
declare var IntroductionMaidOpinion: number;
declare var IntroductionHasBasicItems: boolean;
declare var IntroductionSubRestrained: boolean;
declare var IntroductionIsMaid: boolean;
declare var IntroductionIsHeadMaid: boolean;
declare var IntroductionRescueScenario: string;
declare var IntroductionRescueScenarioList: string[];
declare var IntroductionJobList: string[];
declare var IntroductionJobCurrent: string;
declare var IntroductionJobCount: number;
declare var IntroductionJobParam: any;
declare namespace IntroductionJobPosition {
    const Active: boolean;
    const X: number;
    const Y: number;
}
declare var IntroductionJobLockList: string[];
declare var IntroductionJobSearchList: string[];
declare var IntroductionJobMember: any[];
