declare function PreferenceGetActivityFactor(C: any, Type: any, Self: any): number;
declare function PreferenceSetActivityFactor(C: any, Type: any, Self: any, Factor: any): void;
declare function PreferenceGetZoneFactor(C: any, Zone: any): number;
declare function PreferenceSetZoneFactor(C: any, Zone: any, Factor: any): void;
declare function PreferenceGetZoneOrgasm(C: any, Zone: any): any;
declare function PreferenceSetZoneOrgasm(C: any, Zone: any, CanOrgasm: any): void;
declare function PreferenceGetFactorColor(Factor: any): "#FF000088" | "#FF000044" | "#00FF0044" | "#00FF0088" | "#80808044";
declare function PreferenceArousalIsActive(): boolean;
declare function PreferenceLoadActivityFactor(): void;
declare function PreferenceInit(C: any): void;
declare function PreferenceLoad(): void;
declare function PreferenceRun(): void;
declare function PreferenceClick(): void;
declare function PreferenceExit(): void;
declare function PreferenceSubscreenAudioRun(): void;
declare function PreferenceSubscreenChatRun(): void;
declare function PreferenceSubscreenArousalRun(): void;
declare function PreferenceSubscreenSecurityRun(): void;
declare function PreferenceSubscreenAudioClick(): void;
declare function PreferenceSubscreenChatClick(): void;
declare function PreferenceSubscreenArousalClick(): void;
declare function PreferenceSubscreenSecurityClick(): void;
declare function PreferenceMainScreenLoad(): void;
declare function PreferenceMainScreenExit(): void;
declare function PreferenceIsPlayerInSensDep(): boolean;
declare var PreferenceBackground: string;
declare var PreferenceMessage: string;
declare var PreferenceColorPick: string;
declare var PreferenceSubscreen: string;
declare var PreferenceChatColorThemeSelected: string;
declare var PreferenceChatColorThemeList: string[];
declare var PreferenceChatColorThemeIndex: number;
declare var PreferenceChatEnterLeaveSelected: string;
declare var PreferenceChatEnterLeaveList: string[];
declare var PreferenceChatEnterLeaveIndex: number;
declare var PreferenceChatMemberNumbersSelected: string;
declare var PreferenceChatMemberNumbersList: string[];
declare var PreferenceChatMemberNumbersIndex: number;
declare var PreferenceSettingsSensDepList: string[];
declare var PreferenceSettingsSensDepIndex: number;
declare var PreferenceSettingsVolumeList: number[];
declare var PreferenceSettingsVolumeIndex: number;
declare var PreferenceEmailStatusReceived: boolean;
declare var PreferenceArousalActiveList: string[];
declare var PreferenceArousalActiveIndex: number;
declare var PreferenceArousalVisibleList: string[];
declare var PreferenceArousalVisibleIndex: number;
declare var PreferenceArousalAffectStutterList: string[];
declare var PreferenceArousalAffectStutterIndex: number;
declare var PreferenceArousalActivityList: any;
declare var PreferenceArousalActivityIndex: number;
declare var PreferenceArousalActivityFactorSelf: number;
declare var PreferenceArousalActivityFactorOther: number;
declare var PreferenceArousalZoneFactor: number;
declare var PreferenceCurrentCharacter: any;
declare var PreferenceArousalPreviousModule: any;
declare var PreferenceArousalPreviousScreen: any;
