declare function FriendListLoad(): void;
declare function FriendListRun(): void;
declare function FriendListClick(): void;
declare function FriendListExit(): void;
declare function FriendListLoadFriendList(data: any): void;
declare function FriendListDelete(MemberNumber: any): void;
declare function FriendListBeep(MemberNumber: any, MemberName: any): void;
declare var FriendListBackground: string;
declare var FriendListContent: string;
declare var FriendListConfirmDelete: any[];
declare var FriendListReturn: any;
declare var FriendListMode: string[];
declare var FriendListModeIndex: number;
declare var FriendListShowBeep: number;
declare var FriendListBeepLog: any[];
