declare function HorseWalkGenerateCarrotItems(MaxCarrot: any, MaxCrop: any): void;
declare function HorseWalkGenerateHurdleItems(MaxHurdle: any): void;
declare function HorseWalkGenerateHurdleTrainingItems(MaxHurdle: any): void;
declare function HorseWalkDrawItem(): void;
declare function HorseWalkLoad(): void;
declare function HorseWalkRun(): void;
declare function HorseWalkEnd(Victory: any): void;
declare function HorseWalkDoMove(): void;
declare function HorseWalkClick(): void;
declare var HorseWalkBackground: string;
declare var HorseWalkCarrots: any;
declare var HorseWalkCrops: any;
declare var HorseWalkHurdle: any;
declare var HorseWalkPlayerX: number;
declare var HorseWalkPlayerY: number;
declare var HorseWalkItemSize: number;
declare var HorseWalkCollectedCarrots: number;
declare var HorseWalkCollectedCrops: number;
declare var HorseWalkHurdleWin: number;
declare var HorseWalkHurdleFail: number;
declare var HorseWalkHitPony: number;
declare var HorseWalkHitTrainer: number;
declare var HorseWalkDrawPony: boolean;
declare var HorseWalkDrawTrainer: boolean;
declare var HorseWalkDrawXPosition: number;
declare var HorseWalkDrawYPosition: number;
declare var HorseWalkDrawYHeigh: number;
declare var HorseWalkDrawCaracter: number;
declare var HorseWalkSpeed: number;
declare var HorseWalkText: string;
declare var HorseWalkEventTimer: number;
