declare function AsylumTherapyPatientReadyForTherapy(): any;
declare function AsylumTherapyLoad(): void;
declare function AsylumTherapyRun(): void;
declare function AsylumTherapyClick(): void;
declare function AsylumTherapyPlayerUngag(): void;
declare function AsylumTherapyStripPlayer(): void;
declare function AsylumTherapyBondageTherapyRestrain(): void;
declare function AsylumTherapyTherapyEnd(): void;
declare function AsylumTherapyTherapyFail(): void;
declare function AsylumTherapyTherapySuccess(): void;
declare function AsylumTherapyPainTherapyRestrain(): void;
declare function AsylumTherapyTickleTherapyRestrain(): void;
declare function AsylumTherapyTickleTherapyBlindfold(): void;
declare function AsylumTherapyOrgasmTherapyRestrain(): void;
declare function AsylumTherapyPatientBondageIntro(RepChange: any, RestraintsLevel: any): void;
declare function AsylumTherapyPatientPainIntro(RepChange: any): void;
declare function AsylumTherapyPatientTickleIntro(RepChange: any): void;
declare function AsylumTherapyPatientOrgasmIntro(RepChange: any): void;
declare function AsylumTherapyTherapyStart(Difficulty: any): void;
declare function AsylumTherapyTherapyMiniGameEnd(): void;
declare function AsylumTherapyPatientNew(): void;
declare var AsylumTherapyBackground: string;
declare var AsylumTherapyNurse: any;
declare var AsylumTherapyPatient: any;
